module.exports = {
  dist : {
    src : [
      "src/js/main/utils.js",
      "src/js/main/timer.js",
      "src/js/main/array-modifier.js",
      "src/js/main/crud-adapter.js",
      "src/js/main/model-wrapper.js",
      "src/js/main/app-wrapper.js",
      "src/js/main/column-data.js",
      "src/js/main/global-module.js",
      "src/js/main/listgroups.js",
      "src/js/main/trees.js",
      "src/js/main/lazy-display.js",
      "src/js/main/form.js",
      "src/js/main/alerts.js",
      "src/js/main/dragdrop.js",
      "src/js/main/panels.js",
      "src/js/main/tooltips.js",
      "src/js/main/progress-bars.js",
      "src/js/main/fileupload.js",
      "src/js/main/modal.js",
      "src/js/main/popover.js",
      //"src/js/main/carousel.js",
    ],
    dest : "dist/ember-utils.js",
  },
  test : {
    src : [
      "test/mockapis.js",
      "test/test-utils.js",
      "test/test-init.js",
      "test/timer-unit-test.js",
      "test/array-modifier-unit-test.js",
      "test/columndata-unit-test.js",
      "test/form-unit-test.js",
      "test/modal-unit-test.js",
      "test/crud-adaptor-unit-test.js"
    ],
    dest : "test/tests-merged.js",
  },
};
